export function buildRoadmapPrompt({ careerTarget, skillProfile, analysis }) {
  return [
    "Create a concise career roadmap for SkillBridge.",
    "Use only the deterministic missing skills supplied below.",
    "Do not invent new missing skills.",
    "Order items by the missingSkills order; that order is already ranked by market frequency.",
    "Tie every reason to company evidence, repeated demand, or skillDemand counts from the supplied marketEvidence.",
    "Make each item a portfolio-project sprint, not a generic course plan.",
    "Make each deliverable a concrete portfolio artifact that can improve the student's CV.",
    "Do not invent or return URLs. SkillBridge attaches verified resource links separately.",
    "Return JSON with: overview, items, assumptions, confidence, source.",
    "Each item must include: month, skill, title, learningFocus, tasks, portfolioOutput, what, why, when, howToStart, successCriteria, objective, description, reason, deliverable, resourceSearchQuery, companyEvidence.",
    "learningFocus: return 3-4 concrete topics or subskills for this missing skill.",
    "tasks: return 3-4 project tasks that build visible portfolio evidence.",
    "portfolioOutput: state the finished CV-ready artifact the student should produce.",
    "what: explain the concrete thing the student should learn or build for this missing skill.",
    "why: explain why this skill matters using only company evidence, repeated demand, or skillDemand counts.",
    "when: give a month-level schedule such as 'Month 1: start immediately' or 'Month 2: after SQL basics'.",
    "howToStart: return 3 short first actions the student can do this week.",
    "successCriteria: state what finished CV-ready evidence should exist.",
    "Keep tasks aligned with howToStart for backward compatibility.",
    "Keep wording short enough for visual cards.",
    "",
    JSON.stringify({
      careerTarget,
      education: skillProfile?.education,
      confirmedCvSkills: [
        ...(skillProfile?.technicalSkills ?? []),
        ...(skillProfile?.softSkills ?? []),
        ...(skillProfile?.certifications ?? []),
      ],
      missingSkills: analysis?.missingSkills ?? [],
      marketEvidence: analysis?.marketEvidence ?? {},
    }),
  ].join("\n");
}
